var execSync = require('exec-sync');
var path = require('path');

var user = process.env.USER;
var dataPath = path.resolve(__dirname, 'data');
var fixturePath = path.resolve(__dirname, 'fixtures');

var run = require('../filechains').Workflow.run;

beforeEach(function () {
    execSync('rm -rf ' + dataPath);
    execSync('cp -R ' + fixturePath + ' ' + dataPath);
});

/**
 * The following are functional end-to-end tests. In order for them to work, you need
 * to add your public key to your authorized_keys.
 */
describe('Examples', function(){
    it('should fetch files over rsync, chmod them, and zip them', function(done){
        run([
            { 'fetch files over rsync to autogenerated tmp directory and remove them from source': {
                files: 'rsync://{user}@{host}/{path}',
                using: {
                    user: user,
                    host: 'localhost',
                    path: dataPath + '/in'
                },
                remove: true
            }},
            { 'chmod each file': {
                do: 'chmod 777 {$file}'
            }},
            { 'zip up files': {
                do: 'zip {$dir}/myzipfile {$files}'
            }},
            { 'send zip file over rsync': {
                to: 'rsync://{user}@{host}/tmp',
                match: '*.zip',
                using: {
                    user: user,
                    host: 'localhost'
                }
            }}
        ], { debug: true });
    });
});